### ISSUE TITLE
FlowQueryOperationClassParser dies on missing @return tag

### ISSUE THREAD

**Issue by kdambekalns** [neos/doctools#2]
When https://github.com/neos/doctools/blob/9d77289bf3ae8f9c3020da96dcab1937d812134d/Classes/Domain/Service/FlowQueryOperationClassParser.php#L42 tries to read the `@return` tag but it doesn't exist in the target, the command just dies. Should be checked first, like in e.g. https://github.com/neos/doctools/blob/9d77289bf3ae8f9c3020da96dcab1937d812134d/Classes/Domain/Service/EelHelperClassParser.php#L112

**Comment by dlubitz** [comment]
Fixed with #8
